@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TenantTrack *-right-> "1" UniqueTenantList
TenantTrack *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueTenantList
UniqueTagList -[hidden]down- UniqueTenantList

UniqueTagList -right-> "*" Tag
UniqueTenantList -right-> Tenant

Tenant -up-> "*" Tag

Tenant *--> Name
Tenant *--> Phone
Tenant *--> Email
Tenant *--> Address
Tenant *--> BooleanProperty : isPaid
Tenant *--> BooleanProperty : isArchived
@enduml
