@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "TenantTracker Storage" #F4F6F6{
Class "<<interface>>\nTenantTrackerStorage" as TenantTrackerStorage
Class JsonTenantTrackerStorage
Class JsonSerializableTenantTracker
Class JsonAdaptedTenant
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" TenantTrackerStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> TenantTrackerStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonTenantTrackerStorage .up.|> TenantTrackerStorage
JsonTenantTrackerStorage ..> JsonSerializableTenantTracker
JsonSerializableTenantTracker --> "*" JsonAdaptedTenant
JsonAdaptedTenant --> "*" JsonAdaptedTag

@enduml
