@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TenantTrackerParser" as TenantTrackerParser LOGIC_COLOR
participant ":UnpaidCommandParser" as UnpaidCommandParser LOGIC_COLOR
participant "u:UnpaidCommand" as UnpaidCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("unpaid 98765432")
activate LogicManager

LogicManager -> TenantTrackerParser : parseCommand("unpaid 98765432")
activate TenantTrackerParser

create UnpaidCommandParser
TenantTrackerParser -> UnpaidCommandParser
activate UnpaidCommandParser

UnpaidCommandParser --> TenantTrackerParser
deactivate UnpaidCommandParser

TenantTrackerParser -> UnpaidCommandParser : parse("98765432")
activate UnpaidCommandParser

create UnpaidCommand
UnpaidCommandParser -> UnpaidCommand
activate UnpaidCommand

UnpaidCommand --> UnpaidCommandParser :
deactivate UnpaidCommand

UnpaidCommandParser --> TenantTrackerParser : u
deactivate UnpaidCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
UnpaidCommandParser -[hidden]-> TenantTrackerParser
destroy UnpaidCommandParser

TenantTrackerParser --> LogicManager : u
deactivate TenantTrackerParser

LogicManager -> UnpaidCommand : execute(m)
activate UnpaidCommand

UnpaidCommand -> Model : unmarkTenantAsPaid(98765432)
activate Model

Model --> UnpaidCommand
deactivate Model

create CommandResult
UnpaidCommand -> CommandResult
activate CommandResult

CommandResult --> UnpaidCommand
deactivate CommandResult

UnpaidCommand --> LogicManager : r
deactivate UnpaidCommand

[<--LogicManager
deactivate LogicManager
@enduml
